name: SMILE Research Group
title: SMILE Research Group
url: https://smilevo.github.io/


analytics_enable: true
analytics_id: G-PJ46Z3FFCB

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: visitor
    name: Visiting Researchers
  - key: postdoc
    name: Researchers
  - key: phd
    name: Ph.D. Students
  - key: grad
    name: Graduate Students
  - key: alum
    name: Alumni
  - key: collab
    name: Collaborators
  - key: urop
    name: UROP Students

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''


# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Code
    link: /code.html
  - title: Service
    link: /service.html
